from django_filters import rest_framework as rfilters
from app.models import Player

from django.db.models import ExpressionWrapper, DecimalField, Sum, F

class PlayersFilters(rfilters.FilterSet):

    class Meta:
        model : Player
        fields = ('playerId', 'gamesPlayed', 'players_details_givenName', 'players_details_surname',
    'players_details_heightCm', 'players_details_weightKg', 'players_details_jumperNumber',
    'players_details_kickingFoot', 'players_details_stateOfOrigin', 'players_details_position',
    'players_details_photoURL', 'team_teamName', 'team_teamAbbr', 'team_teamNickname', 'team_teamId',
    'totals_matchesPlayed', 'totals_timeOnGroundPercentage', 'totals_behinds', 'totals_bounces', 'totals_centreClearances',
    'totals_clangers', 'totals_contestDefLosses', 'totals_contestDefLossPercentage', 'totals_contestDefOneOnOnes',
    'totals_contestedMarks', 'totals_contestedPossessionRate', 'totals_contestedPossessions',
    'totals_contestOffOneOnOnes', 'totals_contestOffWins', 'totals_contestOffWinsPercentage',
    'totals_defHalfPressureActs', 'totals_disposalEfficiency', 'totals_disposals', 'totals_dreamTeamPoints',
    'totals_effectiveDisposals', 'totals_effectiveKicks', 'totals_f50GroundBallGets', 'totals_freesAgainst',
    'totals_freesFor', 'totals_goalAccuracy', 'totals_goalAssists', 'totals_goals', 'totals_groundBallGets',
    'totals_handballs', 'totals_hitouts', 'totals_hitoutsToAdvantage', 'totals_hitoutToAdvantageRate',
    'totals_hitoutWinPercentage', 'totals_inside50s', 'totals_interceptMarks', 'totals_intercepts',
    'totals_kickEfficiency', 'totals_kicks', 'totals_kickToHandballRatio', 'totals_marks', 'totals_marksInside50',
    'totals_marksOnLead', 'totals_metresGained', 'totals_onePercenters', 'totals_pressureActs',
    'totals_ranking', 'totals_ratingPoints', 'totals_rebound50s', 'totals_ruckContests', 'totals_scoreInvolvements',
    'totals_scoreLaunches', 'totals_shotsAtGoal', 'totals_spoils', 'totals_stoppageClearances',
    'totals_tackles', 'totals_tacklesInside50', 'totals_totalClearances', 'totals_totalPossessions',
    'totals_turnovers', 'totals_uncontestedPossessions', 'averages_matchesPlayed', 'averages_timeOnGroundPercentage',
    'averages_behinds', 'averages_bounces', 'averages_centreClearances', 'averages_clangers', 'averages_contestDefLosses',
    'averages_contestDefLossPercentage', 'averages_contestDefOneOnOnes', 'averages_contestedMarks', 'averages_contestedPossessionRate',
    'averages_contestedPossessions', 'averages_contestOffOneOnOnes', 'averages_contestOffWins', 'averages_contestOffWinsPercentage',
    'averages_defHalfPressureActs', 'averages_disposalEfficiency', 'averages_disposals', 'averages_dreamTeamPoints', 'averages_effectiveDisposals',
    'averages_effectiveKicks', 'averages_f50GroundBallGets', 'averages_freesAgainst', 'averages_freesFor', 'averages_goalAccuracy', 'averages_goalAssists',
    'averages_goals', 'averages_groundBallGets', 'averages_handballs', 'averages_hitouts', 'averages_hitoutsToAdvantage',
    'averages_hitoutToAdvantageRate', 'averages_hitoutWinPercentage', 'averages_inside50s', 'averages_interceptMarks', 'averages_intercepts',
    'averages_kickEfficiency', 'averages_kicks', 'averages_kickToHandballRatio', 'averages_marks', 'averages_marksInside50', 'averages_marksOnLead',
    'averages_metresGained', 'averages_onePercenters', 'averages_pressureActs', 'averages_ratingPoints', 'averages_rebound50s', 'averages_ruckContests',
    'averages_scoreInvolvements', 'averages_scoreLaunches', 'averages_shotsAtGoal', 'averages_spoils', 'averages_stoppageClearances', 'averages_tackles',
    'averages_tacklesInside50', 'averages_totalClearances', 'averages_totalPossessions', 'averages_turnovers', 'averages_uncontestedPossessions')

    for field in [ 'gamesPlayed',
    'players_details_heightCm', 'players_details_weightKg', 'players_details_jumperNumber',
    'players_details_photoURL','totals_matchesPlayed', 'totals_timeOnGroundPercentage', 'totals_behinds', 'totals_bounces', 'totals_centreClearances',
    'totals_clangers', 'totals_contestDefLosses', 'totals_contestDefLossPercentage', 'totals_contestDefOneOnOnes',
    'totals_contestedMarks', 'totals_contestedPossessionRate', 'totals_contestedPossessions',
    'totals_contestOffOneOnOnes', 'totals_contestOffWins', 'totals_contestOffWinsPercentage',
    'totals_defHalfPressureActs', 'totals_disposalEfficiency', 'totals_disposals', 'totals_dreamTeamPoints',
    'totals_effectiveDisposals', 'totals_effectiveKicks', 'totals_f50GroundBallGets', 'totals_freesAgainst',
    'totals_freesFor', 'totals_goalAccuracy', 'totals_goalAssists', 'totals_goals', 'totals_groundBallGets',
    'totals_handballs', 'totals_hitouts', 'totals_hitoutsToAdvantage', 'totals_hitoutToAdvantageRate',
    'totals_hitoutWinPercentage', 'totals_inside50s', 'totals_interceptMarks', 'totals_intercepts',
    'totals_kickEfficiency', 'totals_kicks', 'totals_kickToHandballRatio', 'totals_marks', 'totals_marksInside50',
    'totals_marksOnLead', 'totals_metresGained', 'totals_onePercenters', 'totals_pressureActs',
    'totals_ranking', 'totals_ratingPoints', 'totals_rebound50s', 'totals_ruckContests', 'totals_scoreInvolvements',
    'totals_scoreLaunches', 'totals_shotsAtGoal', 'totals_spoils', 'totals_stoppageClearances',
    'totals_tackles', 'totals_tacklesInside50', 'totals_totalClearances', 'totals_totalPossessions',
    'totals_turnovers', 'totals_uncontestedPossessions', 'averages_matchesPlayed', 'averages_timeOnGroundPercentage',
    'averages_behinds', 'averages_bounces', 'averages_centreClearances', 'averages_clangers', 'averages_contestDefLosses',
    'averages_contestDefLossPercentage', 'averages_contestDefOneOnOnes', 'averages_contestedMarks', 'averages_contestedPossessionRate',
    'averages_contestedPossessions', 'averages_contestOffOneOnOnes', 'averages_contestOffWins', 'averages_contestOffWinsPercentage',
    'averages_defHalfPressureActs', 'averages_disposalEfficiency', 'averages_disposals', 'averages_dreamTeamPoints', 'averages_effectiveDisposals',
    'averages_effectiveKicks', 'averages_f50GroundBallGets', 'averages_freesAgainst', 'averages_freesFor', 'averages_goalAccuracy', 'averages_goalAssists',
    'averages_goals', 'averages_groundBallGets', 'averages_handballs', 'averages_hitouts', 'averages_hitoutsToAdvantage',
    'averages_hitoutToAdvantageRate', 'averages_hitoutWinPercentage', 'averages_inside50s', 'averages_interceptMarks', 'averages_intercepts',
    'averages_kickEfficiency', 'averages_kicks', 'averages_kickToHandballRatio', 'averages_marks', 'averages_marksInside50', 'averages_marksOnLead',
    'averages_metresGained', 'averages_onePercenters', 'averages_pressureActs', 'averages_ratingPoints', 'averages_rebound50s', 'averages_ruckContests',
    'averages_scoreInvolvements', 'averages_scoreLaunches', 'averages_shotsAtGoal', 'averages_spoils', 'averages_stoppageClearances', 'averages_tackles',
    'averages_tacklesInside50', 'averages_totalClearances', 'averages_totalPossessions', 'averages_turnovers', 'averages_uncontestedPossessions']:
        
        exec(f'min_{field} = rfilters.NumberFilter(field, lookup_expr="gte")')
        exec(f'max_{field} = rfilters.NumberFilter(field, lookup_expr="lte")')

    groupby = rfilters.CharFilter(method='groupby_filter', label='groupby')
    def groupby_filter(self, queryset, name, value):
        return queryset.values(*self.request.query_params.getlist('groupby')).annotate(
            playerId=Sum('playerId'), gamesPlayed=Sum('gamesPlayed'), players_details_givenName=Sum('players_details_givenName'),
            players_details_surname=Sum('players_details_surname'), players_details_heightCm=Sum('players_details_heightCm'),
            players_details_weightKg=Sum('players_details_weightKg'), players_details_jumperNumber=Sum('players_details_jumperNumber'),
            players_details_kickingFoot=Sum('players_details_kickingFoot'), players_details_stateOfOrigin=Sum('players_details_stateOfOrigin'),
            players_details_position=Sum('players_details_position'), players_details_photoURL=Sum('players_details_photoURL'),
            team_teamName=Sum('team_teamName'), team_teamAbbr=Sum('team_teamAbbr'), team_teamNickname=Sum('team_teamNickname'),
            team_teamId=Sum('team_teamId'), totals_matchesPlayed=Sum('totals_matchesPlayed'), totals_timeOnGroundPercentage=Sum('totals_timeOnGroundPercentage'),
            totals_behinds=Sum('totals_behinds'), totals_bounces=Sum('totals_bounces'), totals_centreClearances=Sum('totals_centreClearances'),
            totals_clangers=Sum('totals_clangers'), totals_contestDefLosses=Sum('totals_contestDefLosses'), totals_contestDefLossPercentage=Sum('totals_contestDefLossPercentage'),
            totals_contestDefOneOnOnes=Sum('totals_contestDefOneOnOnes'), totals_contestedMarks=Sum('totals_contestedMarks'),
            totals_contestedPossessionRate=Sum('totals_contestedPossessionRate'), totals_contestedPossessions=Sum('totals_contestedPossessions'),
            totals_contestOffOneOnOnes=Sum('totals_contestOffOneOnOnes'), totals_contestOffWins=Sum('totals_contestOffWins'),
            totals_contestOffWinsPercentage=Sum('totals_contestOffWinsPercentage'), totals_defHalfPressureActs=Sum('totals_defHalfPressureActs'),
            totals_disposalEfficiency=Sum('totals_disposalEfficiency'), totals_disposals=Sum('totals_disposals'),
            totals_dreamTeamPoints=Sum('totals_dreamTeamPoints'), totals_effectiveDisposals=Sum('totals_effectiveDisposals'),
            totals_effectiveKicks=Sum('totals_effectiveKicks'), totals_f50GroundBallGets=Sum('totals_f50GroundBallGets'),
            totals_freesAgainst=Sum('totals_freesAgainst'), totals_freesFor=Sum('totals_freesFor'), totals_goalAccuracy=Sum('totals_goalAccuracy'),
            totals_goalAssists=Sum('totals_goalAssists'), totals_goals=Sum('totals_goals'), totals_groundBallGets=Sum('totals_groundBallGets'), 
            totals_handballs=Sum('totals_handballs'), totals_hitouts=Sum('totals_hitouts'), totals_hitoutsToAdvantage=Sum('totals_hitoutsToAdvantage'), 
            totals_hitoutToAdvantageRate=Sum('totals_hitoutToAdvantageRate'), totals_hitoutWinPercentage=Sum('totals_hitoutWinPercentage'),
            totals_inside50s=Sum('totals_inside50s'), totals_interceptMarks=Sum('totals_interceptMarks'), totals_intercepts=Sum('totals_intercepts'),
            totals_kickEfficiency=Sum('totals_kickEfficiency'), totals_kicks=Sum('totals_kicks'), totals_kickToHandballRatio=Sum('totals_kickToHandballRatio'),
            totals_marks=Sum('totals_marks'), totals_marksInside50=Sum('totals_marksInside50'), totals_marksOnLead=Sum('totals_marksOnLead'),
            totals_metresGained=Sum('totals_metresGained'), totals_onePercenters=Sum('totals_onePercenters'), totals_pressureActs=Sum('totals_pressureActs'),
            totals_ranking=Sum('totals_ranking'), totals_ratingPoints=Sum('totals_ratingPoints'), totals_rebound50s=Sum('totals_rebound50s'),
            totals_ruckContests=Sum('totals_ruckContests'), totals_scoreInvolvements=Sum('totals_scoreInvolvements'),
            totals_scoreLaunches=Sum('totals_scoreLaunches'), totals_shotsAtGoal=Sum('totals_shotsAtGoal'),
            totals_spoils=Sum('totals_spoils'), totals_stoppageClearances=Sum('totals_stoppageClearances'), 
            totals_tackles=Sum('totals_tackles'), totals_tacklesInside50=Sum('totals_tacklesInside50'), 
            totals_totalClearances=Sum('totals_totalClearances'), totals_totalPossessions=Sum('totals_totalPossessions'),
            totals_turnovers=Sum('totals_turnovers'), totals_uncontestedPossessions=Sum('totals_uncontestedPossessions'),
            averages_matchesPlayed=Sum('averages_matchesPlayed'), averages_timeOnGroundPercentage=Sum('averages_timeOnGroundPercentage'),
            averages_behinds=Sum('averages_behinds'), averages_bounces=Sum('averages_bounces'), averages_centreClearances=Sum('averages_centreClearances'),
            averages_clangers=Sum('averages_clangers'), averages_contestDefLosses=Sum('averages_contestDefLosses'),
            averages_contestDefLossPercentage=Sum('averages_contestDefLossPercentage'), averages_contestDefOneOnOnes=Sum('averages_contestDefOneOnOnes'),
            averages_contestedMarks=Sum('averages_contestedMarks'), averages_contestedPossessionRate=Sum('averages_contestedPossessionRate'),
            averages_contestedPossessions=Sum('averages_contestedPossessions'), averages_contestOffOneOnOnes=Sum('averages_contestOffOneOnOnes'), 
            averages_contestOffWins=Sum('averages_contestOffWins'), averages_contestOffWinsPercentage=Sum('averages_contestOffWinsPercentage'), 
            averages_defHalfPressureActs=Sum('averages_defHalfPressureActs'), averages_disposalEfficiency=Sum('averages_disposalEfficiency'), 
            averages_disposals=Sum('averages_disposals'), averages_dreamTeamPoints=Sum('averages_dreamTeamPoints'), 
            averages_effectiveDisposals=Sum('averages_effectiveDisposals'), averages_effectiveKicks=Sum('averages_effectiveKicks'), 
            averages_f50GroundBallGets=Sum('averages_f50GroundBallGets'), averages_freesAgainst=Sum('averages_freesAgainst'), 
            averages_freesFor=Sum('averages_freesFor'), averages_goalAccuracy=Sum('averages_goalAccuracy'), averages_goalAssists=Sum('averages_goalAssists'),
            averages_goals=Sum('averages_goals'), averages_groundBallGets=Sum('averages_groundBallGets'), averages_handballs=Sum('averages_handballs'), 
            averages_hitouts=Sum('averages_hitouts'), averages_hitoutsToAdvantage=Sum('averages_hitoutsToAdvantage'), 
            averages_hitoutToAdvantageRate=Sum('averages_hitoutToAdvantageRate'), averages_hitoutWinPercentage=Sum('averages_hitoutWinPercentage'), 
            averages_inside50s=Sum('averages_inside50s'), averages_interceptMarks=Sum('averages_interceptMarks'), averages_intercepts=Sum('averages_intercepts'), 
            averages_kickEfficiency=Sum('averages_kickEfficiency'), averages_kicks=Sum('averages_kicks'), 
            averages_kickToHandballRatio=Sum('averages_kickToHandballRatio'), averages_marks=Sum('averages_marks'), 
            averages_marksInside50=Sum('averages_marksInside50'), averages_marksOnLead=Sum('averages_marksOnLead'), 
            averages_metresGained=Sum('averages_metresGained'), averages_onePercenters=Sum('averages_onePercenters'), 
            averages_pressureActs=Sum('averages_pressureActs'), averages_ratingPoints=Sum('averages_ratingPoints'), 
            averages_rebound50s=Sum('averages_rebound50s'), averages_ruckContests=Sum('averages_ruckContests'), 
            averages_scoreInvolvements=Sum('averages_scoreInvolvements'), averages_scoreLaunches=Sum('averages_scoreLaunches'), 
            averages_shotsAtGoal=Sum('averages_shotsAtGoal'), averages_spoils=Sum('averages_spoils'), averages_stoppageClearances=Sum('averages_stoppageClearances'), averages_tackles=Sum('averages_tackles'),
            averages_tacklesInside50=Sum('averages_tacklesInside50'), averages_totalClearances=Sum('averages_totalClearances'), averages_totalPossessions=Sum('averages_totalPossessions'),
            averages_turnovers=Sum('averages_turnovers'), averages_uncontestedPossessions=Sum('averages_uncontestedPossessions')

        )
