from rest_framework import  serializers
from app.models import Player

class PlayerSerializer(serializers.ModelSerializer):
    playerId = serializers.CharField( max_length=200, required=False)
    gamesPlayed = serializers.FloatField()
    players_details_givenName = serializers.CharField(max_length=200, required=False)
    players_details_surname= serializers.CharField(max_length=200, required=False)
    players_details_heightCm = serializers.IntegerField()
    players_details_weightKg = serializers.IntegerField()
    players_details_jumperNumber = serializers.IntegerField()
    players_details_kickingFoot = serializers.CharField(max_length=200, required=False)
    players_details_stateOfOrigin = serializers.CharField(max_length=200, required=False)
    players_details_position = serializers.CharField(max_length=200, required=False)
    players_details_photoURL = serializers.URLField(max_length=200, required=False)
    team_teamName = serializers.CharField(max_length=200, required=False)
    team_teamAbbr = serializers.CharField(max_length=200, required=False)
    team_teamNickname = serializers.CharField(max_length=200, required=False)
    team_teamId = serializers.CharField(max_length=200, required=False)
    totals_matchesPlayed = serializers.FloatField()
    totals_timeOnGroundPercentage = serializers.FloatField()
    totals_behinds = serializers.FloatField()
    totals_bounces = serializers.FloatField()
    totals_centreClearances = serializers.FloatField()
    totals_clangers = serializers.FloatField()
    totals_contestDefLosses = serializers.FloatField()
    totals_contestDefLossPercentage = serializers.FloatField()
    totals_contestDefOneOnOnes = serializers.FloatField()
    totals_contestedMarks = serializers.FloatField()
    totals_contestedPossessionRate = serializers.FloatField()
    totals_contestedPossessions = serializers.FloatField()
    totals_contestOffOneOnOnes = serializers.FloatField()
    totals_contestOffWins = serializers.FloatField()
    totals_contestOffWinsPercentage = serializers.FloatField()
    totals_defHalfPressureActs = serializers.FloatField()
    totals_disposalEfficiency = serializers.FloatField()
    totals_disposals = serializers.FloatField()
    totals_dreamTeamPoints = serializers.FloatField()
    totals_effectiveDisposals = serializers.FloatField()
    totals_effectiveKicks = serializers.FloatField()
    totals_f50GroundBallGets = serializers.FloatField()
    totals_freesAgainst = serializers.FloatField()
    totals_freesFor = serializers.FloatField()
    totals_goalAccuracy = serializers.FloatField()
    totals_goalAssists = serializers.FloatField()
    totals_goals = serializers.FloatField()
    totals_groundBallGets = serializers.FloatField()
    totals_handballs = serializers.FloatField()
    totals_hitouts = serializers.FloatField()
    totals_hitoutsToAdvantage = serializers.FloatField()
    totals_hitoutToAdvantageRate = serializers.FloatField()
    totals_hitoutWinPercentage = serializers.FloatField()
    totals_inside50s = serializers.FloatField()
    totals_interceptMarks = serializers.FloatField()
    totals_intercepts = serializers.FloatField()
    totals_kickEfficiency = serializers.FloatField()
    totals_kicks = serializers.FloatField()
    totals_kickToHandballRatio = serializers.FloatField()
    totals_marks = serializers.FloatField()
    totals_marksInside50 = serializers.FloatField()
    totals_marksOnLead = serializers.FloatField()
    totals_metresGained = serializers.FloatField()
    totals_onePercenters = serializers.FloatField()
    totals_pressureActs = serializers.FloatField()
    totals_ranking = serializers.FloatField()
    totals_ratingPoints = serializers.FloatField()
    totals_rebound50s = serializers.FloatField()
    totals_ruckContests = serializers.FloatField()
    totals_scoreInvolvements = serializers.FloatField()
    totals_scoreLaunches = serializers.FloatField()
    totals_shotsAtGoal = serializers.FloatField()
    totals_spoils = serializers.FloatField()
    totals_stoppageClearances = serializers.FloatField()
    totals_tackles = serializers.FloatField()
    totals_tacklesInside50 = serializers.FloatField()
    totals_totalClearances = serializers.FloatField()
    totals_totalPossessions = serializers.FloatField()
    totals_turnovers = serializers.FloatField()
    totals_uncontestedPossessions = serializers.FloatField()
    averages_matchesPlayed = serializers.FloatField()
    averages_timeOnGroundPercentage = serializers.FloatField()
    averages_behinds = serializers.FloatField()
    averages_bounces = serializers.FloatField()
    averages_centreClearances = serializers.FloatField()
    averages_clangers = serializers.FloatField()
    averages_contestDefLosses = serializers.FloatField()
    averages_contestDefLossPercentage = serializers.FloatField()
    averages_contestDefOneOnOnes = serializers.FloatField()
    averages_contestedMarks = serializers.FloatField()
    averages_contestedPossessionRate = serializers.FloatField()
    averages_contestedPossessions = serializers.FloatField()
    averages_contestOffOneOnOnes = serializers.FloatField()
    averages_contestOffWins = serializers.FloatField()
    averages_contestOffWinsPercentage = serializers.FloatField()
    averages_defHalfPressureActs = serializers.FloatField()
    averages_disposalEfficiency = serializers.FloatField()
    averages_disposals = serializers.FloatField()
    averages_dreamTeamPoints = serializers.FloatField()
    averages_effectiveDisposals = serializers.FloatField()
    averages_effectiveKicks = serializers.FloatField()
    averages_f50GroundBallGets = serializers.FloatField()
    averages_freesAgainst = serializers.FloatField()
    averages_freesFor = serializers.FloatField()
    averages_goalAccuracy = serializers.FloatField()
    averages_goalAssists = serializers.FloatField()
    averages_goals = serializers.FloatField()
    averages_groundBallGets = serializers.FloatField()
    averages_handballs = serializers.FloatField()
    averages_hitouts = serializers.FloatField()
    averages_hitoutsToAdvantage = serializers.FloatField()
    averages_hitoutToAdvantageRate = serializers.FloatField()
    averages_hitoutWinPercentage = serializers.FloatField()
    averages_inside50s = serializers.FloatField()
    averages_interceptMarks = serializers.FloatField()
    averages_intercepts = serializers.FloatField()
    averages_kickEfficiency = serializers.FloatField()
    averages_kicks = serializers.FloatField()
    averages_kickToHandballRatio = serializers.FloatField()
    averages_marks = serializers.FloatField()
    averages_marksInside50 = serializers.FloatField()
    averages_marksOnLead = serializers.FloatField()
    averages_metresGained = serializers.FloatField()
    averages_onePercenters = serializers.FloatField()
    averages_pressureActs = serializers.FloatField()
    averages_ratingPoints = serializers.FloatField()
    averages_rebound50s = serializers.FloatField()
    averages_ruckContests = serializers.FloatField()
    averages_scoreInvolvements = serializers.FloatField()
    averages_scoreLaunches = serializers.FloatField()
    averages_shotsAtGoal = serializers.FloatField()
    averages_spoils = serializers.FloatField()
    averages_stoppageClearances = serializers.FloatField()
    averages_tackles = serializers.FloatField()
    averages_tacklesInside50 = serializers.FloatField()
    averages_totalClearances = serializers.FloatField()
    averages_totalPossessions = serializers.FloatField()
    averages_turnovers = serializers.FloatField()
    averages_uncontestedPossessions = serializers.FloatField()

    class Meta:
        model = Player
        fields = ('playerId', 'gamesPlayed', 'players_details_givenName', 'players_details_surname', 'players_details_heightCm', 'players_details_weightKg', 'players_details_jumperNumber', 'players_details_kickingFoot', 'players_details_stateOfOrigin', 'players_details_position', 'players_details_photoURL', 'team_teamName', 'team_teamAbbr', 'team_teamNickname', 'team_teamId', 'totals_matchesPlayed', 'totals_timeOnGroundPercentage', 'totals_behinds', 'totals_bounces', 'totals_centreClearances', 'totals_clangers', 'totals_contestDefLosses', 'totals_contestDefLossPercentage', 'totals_contestDefOneOnOnes', 'totals_contestedMarks', 'totals_contestedPossessionRate', 'totals_contestedPossessions', 'totals_contestOffOneOnOnes', 'totals_contestOffWins', 'totals_contestOffWinsPercentage', 'totals_defHalfPressureActs', 'totals_disposalEfficiency', 'totals_disposals', 'totals_dreamTeamPoints', 'totals_effectiveDisposals', 'totals_effectiveKicks', 'totals_f50GroundBallGets', 'totals_freesAgainst', 'totals_freesFor', 'totals_goalAccuracy', 'totals_goalAssists', 'totals_goals', 'totals_groundBallGets', 'totals_handballs', 'totals_hitouts', 'totals_hitoutsToAdvantage', 'totals_hitoutToAdvantageRate', 'totals_hitoutWinPercentage', 'totals_inside50s', 'totals_interceptMarks', 'totals_intercepts', 'totals_kickEfficiency', 'totals_kicks', 'totals_kickToHandballRatio', 'totals_marks', 'totals_marksInside50', 'totals_marksOnLead', 'totals_metresGained', 'totals_onePercenters', 'totals_pressureActs', 'totals_ranking', 'totals_ratingPoints', 'totals_rebound50s', 'totals_ruckContests', 'totals_scoreInvolvements', 'totals_scoreLaunches', 'totals_shotsAtGoal', 'totals_spoils', 'totals_stoppageClearances', 'totals_tackles', 'totals_tacklesInside50', 'totals_totalClearances', 'totals_totalPossessions', 'totals_turnovers', 'totals_uncontestedPossessions', 'averages_matchesPlayed', 'averages_timeOnGroundPercentage', 'averages_behinds', 'averages_bounces', 'averages_centreClearances', 'averages_clangers', 'averages_contestDefLosses', 'averages_contestDefLossPercentage', 'averages_contestDefOneOnOnes', 'averages_contestedMarks', 'averages_contestedPossessionRate', 'averages_contestedPossessions', 'averages_contestOffOneOnOnes', 'averages_contestOffWins', 'averages_contestOffWinsPercentage', 'averages_defHalfPressureActs', 'averages_disposalEfficiency', 'averages_disposals', 'averages_dreamTeamPoints', 'averages_effectiveDisposals', 'averages_effectiveKicks', 'averages_f50GroundBallGets', 'averages_freesAgainst', 'averages_freesFor', 'averages_goalAccuracy', 'averages_goalAssists', 'averages_goals', 'averages_groundBallGets', 'averages_handballs', 'averages_hitouts', 'averages_hitoutsToAdvantage', 'averages_hitoutToAdvantageRate', 'averages_hitoutWinPercentage', 'averages_inside50s', 'averages_interceptMarks', 'averages_intercepts', 'averages_kickEfficiency', 'averages_kicks', 'averages_kickToHandballRatio', 'averages_marks', 'averages_marksInside50', 'averages_marksOnLead', 'averages_metresGained', 'averages_onePercenters', 'averages_pressureActs', 'averages_ratingPoints', 'averages_rebound50s', 'averages_ruckContests', 'averages_scoreInvolvements', 'averages_scoreLaunches', 'averages_shotsAtGoal', 'averages_spoils', 'averages_stoppageClearances', 'averages_tackles', 'averages_tacklesInside50', 'averages_totalClearances', 'averages_totalPossessions', 'averages_turnovers', 'averages_uncontestedPossessions')