# Generated by Django 3.1.4 on 2020-12-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table='afl_players_data',
        ),
    ]
