# Generated by Django 3.1.4 on 2020-12-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201216_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerId',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
