# Generated by Django 3.1.4 on 2020-12-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201216_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gamesPlayed',
            field=models.FloatField(),
        ),
    ]
