# Generated by Django 3.1.4 on 2020-12-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201216_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_teamId',
            field=models.CharField(max_length=200),
        ),
    ]
